### ISSUE TITLE
SampleThreadPool thread safety

### ISSUE THREAD

**Issue by martinfinke** [christophhart/HISE#106]
In `~SampleThreadPool()`, the `pimpl` is deleted *before* stopping the background thread. I could be missing some external synchronization/safety here, but it looks like a race condition:

1. `~SampleThreadPool()` does `pimpl = nullptr;`
2. The thread could still be running, so `run()` [calls `pimpl->jobQueue.peek()`](https://github.com/christophhart/HISE/blob/master/hi_streaming/hi_streaming/SampleThreadPool.cpp#L112) for example, which is a null pointer dereference.
3. `~SampleThreadPool()` calls `stopThread`. After that has returned, we know that the thread isn't running anymore.

I get crash reports in `SampleThreadPool::run()`, while the main thread is inside `~SampleThreadPool()`.

A solution could be to use [atomic shared_ptr](https://en.cppreference.com/w/cpp/memory/shared_ptr/atomic), keeping a local `shared_ptr<Pimpl>` inside `run()`'s `while` loop.

**Comment by martinfinke** [comment]
> it looks like a race condition

The crash can be reproduced reliably by adding a sleep:

```cpp
SampleThreadPool::~SampleThreadPool()
{
	pimpl = nullptr;
    
	Thread::sleep(3000);

	stopThread(300);
}
```

It then crashes consistently in `SampleThreadPool::run()` because `pimpl` is `nullptr`. Of course, the destructor "never" takes 3 seconds, it just shows that you can't rely on the background thread not accessing `pimpl` there.

**Comment by christophhart** [comment]
Alright, thanks. What if you simply exchange the lines?

```cpp
stopThread(1000); // more is better
pimpl = nullptr;
```

**Comment by martinfinke** [comment]
There's another race [here]( https://github.com/christophhart/HISE/blob/master/hi_streaming/hi_streaming/SampleThreadPool.cpp#L114). Calling `ConcurrentQueue::peek()` is thread-safe, but calling `WeakReference<Job>::get()` isn't.

A thread-safe way would be to use `ConcurrentQueue::try_dequeue()` to get a local copy of the `WeakReference<Job>`, but then it's not possible to keep `Job`s in the queue until `jobHasFinished `. I'm not 100% sure if that's important.

**Comment by christophhart** [comment]
Sorry, took me a while to get back here. I fixed the order in the destructor, so it shouldn't crash anymore now.

You're right about the `try_dequeue` being more safe than peeking the pointer (I can imagine that this race condition is a bit theoretical, but if it makes Thread Sanitizer happy, then I am fine with the change). I've changed this too. There shouldn't be any issues with pushing it back to the queue if it needs running again (if it checks if it's currently being executed, it uses one of the atomic flags) - the only thing is that the reexecution has to wait until the other jobs are done, but in this scenario, you'll be in trouble anyway.

RE: the resetVoice(): if you're using monoliths (which I know you do), there is no deferred action launched on the streaming thread so you can definitely reuse the voices after calling `StreamingSamplerVoice::resetVoice()`- however if you use single audio files, it might happen that the file handles need to be closed (because funky macOS can't open more than ~242 files in certain sandboxed hosts) and this can't be done on the audio thread. In this case, it will launch Unmapper::runJob(), which closes the file handles (which is like any other OS call non-deterministic in its execution time).

This is the commit that fixes everything addressed here:

https://github.com/christophhart/HISE/commit/8ac9de96d0b11945ec31ab7da5bac4f7989b4241

 I am going to close the issue, feel free to reopen if there is something left.

**Comment by martinfinke** [comment]
No problem, and thanks for all the details!

Yeah, the point with that race condition is to keep Thread Sanitizer clean, and maybe not having to remember / comment that it's not-critical, when reading the code again in a few months.
