### ISSUE TITLE
More than 9 Scriptnode FX Parameters unavailable by attribute ID

### ISSUE THREAD

**Issue by crdspace** [christophhart/HISE#252]
### Forum discussion ###

https://forum.hise.audio/topic/5225/scriptnode-parameter-issue

### Commit ###

b00bc8f

### Conditions to reproduce the bug ###

OS: MacOS
HISE: yes
Compiled Project: yes

Calling parameters by attribute number works correctly, but calling Scriptnode parameters by attribute ID only works correctly for the first 8 parameters.

### Snippet ###
```
HiseSnippet 1613.3oc2Xs0aaTDEd13LoMoWfVEg.IDrJhGbTSirMkVPkpb0txpMIlrtoHdoZxtiiGkcmYY1YShaER7.+d3u.7CfG3u.ugDuzW3Y3Lytq85TaWWiSUE4gnctbNy24aNy4haHEtznHgDYMeyNgTj0UwNc3p1a0lv3n5airdObjqjEp3BO5lwGg1rSHIJh5grrJ7P8lrleVj4uWt1lDeB2k1aJD5.Ayk9XV.S0a1Fq+HlueMhGsIKH2tuy50cE7sD9hX.PEvkPgD2iIGQ2kn21LXj0bU8XJgzQQTzHj0raJ753zVbJOY+GvhXG5S0CJib.EkLcMgumFw5YQa0l460HyviPHKbidzPgDZXQ7NLOV246QGuuYA6dRjmOrloe3UnO3UdXva.PxJGjlMAR2.6XtH5shFOWAWmqnxVDf1yCkj8hlwZV7VBXGb0pAjio0jvftRT7tkJshM7uku+BK.Tejx9DhzNQ1p7Sn9hP5NBuXeBXUksefsw4X0inptyVbojsamse6dBrjVusDR6hrGT591rudXZVqwciC1PojrCiAtq3xv1u0sVdgWrv7.9iD9zUCkLtp3nTQW4q6UjsLb3+vBKjY8DOuGSNj5WbomJjGGcamtd01MHRvAC3D6xKshMvHZ9nGc7Ht3PssmSS5oJtjYgDIpXnvW8rpJkB4PNqRIhduW8zpLrSqRhHek4zXbeFmZ2Jl6pXBtsfa.jVPovunqHHTvAUrBnW+XpgKGJ6Eki8FNGuGmloMfbyYw.4uU14kQLKqUZJZ1h36eH7XtX+fTaFCwNpbQZGMo7w0NpLl1QN3uqPQ2iWz.TvEz97K0p0.WKUW9T4.WVGqTNJAKxiCNjJySS5MBAP5OpDd7hJ4lPI41nfWmyT6ER4CKTJJkGgHXyjhJXqJS7qqmF+xwm4QkHFDl5RXCIhL.NMOvO9WeyetFZrEtReB+q+cweaMzSpuMQQzQQSgC.wPpTwzVu01zSfTRIwTmGuMM5XkHDHot26v2IG50ROTyaYyY9I3QE7.cFPtV5LYcx9.kSqW80xC8K+hvGQpN5al4La.Ev777oMDQL8MetLu+RjhF5vdtgGdwh+7C+im+SqEjO4LBEPNKet5n3VsXmYxp1h4GDAuYBqG.IaQV2D+jHpsGsEI1WYGcLnG3E5wTulBy9QiCU8o3QF66b1Zs2Ptpx4j+6dmkqd0D4PIDYQhxWWgtXpzEz.NexbcBaNXHcxCpyWrwrC+YcowtVnwEt2.2fobaOX7Ny.vqNhvELdSKc6Z3psZQcU8.6r3Ze6HqSapCkqm.kqfcfLalZlL.4CLiseJ4Dp8CobpzjMZDkT+6iaI0gicI064pfiuojviBEQ8oXGZ.qI7.LJ+jf6cMI862WeKme9sDD4.W5kqUCLxAJiCQEKMtKaDHh4p9bOJL12ICtz9AVG8rWTk1+V801+8fCSmNQlOCiNrfPeZVgUFLdSHUpIHX1r86WuifKBaK3L27W56SgPoGcDUlG6Czffh5fxt5MyhquO0mRx6.+Yq+XvwiHAdhdwyEi595CwIv0V+Xz9+GA0KLVA0mNb6kS.4GgGRA7Fz9w3g234j55sIKT3SjCMGVZW0VqfeSp+FOk3ndUWi1kpNUWIpl3R+FtaShU3vYggTU0yH5GonM78Em1P32IiCzGiYRc8VrzaZfmRFRA+ANm5mEgFaMi4ddWyqp4pQbASoSCBjRCbXzMI.tOT4pt4hVcNDz6xv30BVd2JAiRfiV4YIoRppC.SfoRP8u5SA85FG4dxAYW6NJ0zwXn+TzNL9AIsDfwkVsDZGxYcGWFFePt9ER7g0sIvolay9Njtps4ohwUsICdcp7R3lskT5zUoygqoIvosNYmLkwIFReb1zlOcnm.skNkUZU1QsUSaBcWFepSnMGeaOWtlWiZuLtp+TfU606cRPd8HHn5L5i3p35QGnW0k3moFHdylBwwADS3sIpY92k5JXeQrhwOZGBjtQ2y5twANvyT2r3rQYgXSGWJKBnCk6YF7OveoKVVO1JcwxYK9V4LBHtRwybSR0ouKurYFvt4lec94w6nGa28WyIwWAZCm8LWWMce6xHzfkoxDHymOAxbmIPluXBj4tSfL2aBj4KGoL5tY1HVIBRxvCSznp4sjkUUNA7jMd8n+EnHSVTI
```

**Comment by Matt-Dub** [comment]
**Commit** : a36188f4162ab20e96a7061133684f8add8e9168
**OS** : Win 10

Fixed a typo on line 26 + Note that if you add 2 more parameters after the one you want to control (here the "Ten"), it works. Otherwise, the parameter doesn't appear in the Property Editor and the console outputs "API call with undefined parameter".

`HiseSnippet 1711.3oc0Ys0aaTDEd2jLoIoWnEUg.IDrxhGbTSirMkVfRTbtXWY0lDqrto.uTMd833QY2YV1cbRbQHwC7OgG3uQ+Iz23Yj3GPegmgyLydM01I00En9gHOWNmy246blybFmlAbGRXHOvvbwVC7IFlWAYOfI5sUOLkYzXaCy2CE5DP8ELdGxl8OzXyA93vPRGCSyYefbSlKNmg5yKWeSrKl4PRmxv3.N0g7HpGUjNaypOj55VG2gzh5kY22oZCGNaKtKuO.nYQkL7wNGgOjrKVtsYPFlyWqCUvCrEXAIzvbtM4cFX2ieBSu+Cngz1tD4fxF1fhzSWm61QhX4rFa0i51oYriGZXXhZlRCypogah1g1glLeJcbc0BVoRjkOLmIO7lMG7JmEdkx.ug.IyLPZNMjtAxVEHRWQhmKiZvDjftXf1yBE8dMl42lCsEG1ASrpG9HR8.XPhDEuaoRqXA+Y46uzR.0GJrNFGXoksF6XhK2mrCuSeWL3UksVyRkbr5gDQxrEKn2tU79sREnfTuc4AVEoqU59VzuYTZVpwc66sgPDPa2G3thKCa+V2Z4k9wkVDveH2krpe.kIJNNUjHeiNEoKCF+mVZoXuG2oyivsItEK7DdvQg21NIq1pIN.Rv.NwpbgUr.FQxGozwCY71ReOiljSUrfZAsDUTT3qZqZAA7fQXqRZQu2qZsJixZUzh7UmIfsE2qMeS9oYQIPGvz9bFLnXgjcnBITlKkQr51m4HnblEmobEonAb2hNwxsBnc29DUTXj7dXFdezQm8XjXsAgkLbUdbpozkkJMBMagccaCkAJlGjR2XD9Qkw5GILgzxGHmt3xVqslUYq0sdC8wVDVrkr952TkUykbbp9NONqx33rJobVFpZWtfrGqnhTfCJVmcotcG5ZQ5xkDLzkkUzCFmfEY88ZSBxFRjaDJyku1IZz0NyVZ2QSIY1Hm0fQE64SXipfuQDOB0YmMBUv2DpprWKpJqsKsCIvfBESuDRk3Yn.b7sU+9u9h0MtvBWImvO+uJ9mupvWOR33DTk3WFkjul29xqaMdbiswBr75hHOB7ReRffJIPysIGC28pu7XQz1jviDbefXSRc.NWa5qFYZUQKkc+Dz3pRZbJnFSIHFD+EiLZc9ykJyK+MguDJH91zmE6eU+im8Kq6GGyZ.h9wnQeOSNqORe5SQisZ7Y.U8y3TnyMDmW9ueDNUVctvELxeZRT+4sqNHME36p5gUVcFX.UP7fvdEjMwk3HrJ.kir7icvBKEOstvRgzkLNg1QzKQq+7gU6BYSYvM7YkpFuZGIPuPwgfrMHI6JLZA3jettRjcdvBohAYSimZcMcQg3MPMoBmdCGiyLDLBmvdafwndMuJpV2tPnIEfygp+sucZrLq4ul17WFYCWhpZrSY7OPM15I3iIVOfvHA5iXitu+WbQ662+B22+dNBv7sBvrPedXNEaS7nsfyOgYm7wgPmsjeXeYzL67awwACcoWtdcvIGpL1XQ+.UZwFd79LQtzfYG26OJOgu+Xt+289i2ANrm6IRKFiQapmuKI9JBEFee3put39tIMYkOWdGNi62iynNYCz6SfFzN7PRPVrOTGBZkC5zJclaVcenPKNaR6mU8QPxFN.3IxDxEkeset3PiWeHRCWK4APq2cKRO6a2hz43yEzf7iPinUcEZGa2ISX51lTetKNXj2IE8DeyUPuNsYilR4boMQarKQbhraQIwE8cH1pqOXyn99DQsSwxClFa35xOoI2cPLGHMiZRYaQznHsorub4PBjOvXD23Jw5NcLmYW0Io4qic.WYPSrr8kafjuE.ReHAq5joB0YPPZvPkE.ddRSfgZ3HUd7kQ5F5.v3oZXS9SPMqbcUhbpbFlWIYTjqiPvSdM1gxNP21NBUZ0RF6fOMYbYX7A46oOpUdFQEMyYjD015D9EUs5AmmJuDpUu.BY5pz4Q0kD3zVmzimx3DAWYb5zlOskcXOsUZM5g8DSaBcWJapSnst39dl6WNG0t.R+tkoFXmWq0VmPbykSkdTLUyovzN+K5z0gOhbhtRT1cd9dX5a00W3HGAE3mQBrqfZDdfbUGrarKA091jyOxCqJ0NQO9++5WerOuufxNbGLbcm7gq612yFJS3DWmOLtDez3RwUfsIrNpA+M7IZwxxwlQKVNdw+UrgG1If+TG8Usx32BpY.+lo9WUrHZG4XqjezFctpGz59ScbjT7sgWBLbYpLAx74SfL2YBj4Kl.Yt6DHy8l.Y9xwJi7USazWv8zcX.Szrl57ioYMFFxdUY5F+ClagZFB`

**Comment by christoph-hart** [comment]
I'll flag this as low priority because there is a workaround (using magic numbers) for now plus the fix is not trivial to do (the problem is the amount of constants that a scripting object can have and I have to think about a way to allow more constants without bloating 99% of all objects that don't need this many.
