### ISSUE TITLE
Token Select via CTRL+D Doesn't Match Selection Highlight

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#455]
CTRL+D selection doesn't match the displayed highlighted matches for selected tokens. 

Highlights are only for complete tokens, while CTRL+D will select partial as well.

![hise highlight](https://github.com/christophhart/HISE/assets/141569073/c2dedeb8-0f34-4efd-b07b-99f646e0ea01)

**Comment by christoph-hart** [comment]
Hmm, there's a mismatch between how Sublime and VS handles this so the world hasn't reached a verdict here and I picked the Sublime one:

Sublime:

![sub](https://github.com/christophhart/HISE/assets/6277426/668d1d32-fdd7-4eb1-af9d-95e4e6c1da20)

VS:

![sub2](https://github.com/christophhart/HISE/assets/6277426/9c9b93e9-3c16-422e-8e45-b22bcc203635)

HISE:

![sub3](https://github.com/christophhart/HISE/assets/6277426/35623a49-340d-466e-8b53-563765b625ba)

I find the current implementation more practical for my workflow: I'm using the double click to highlight function whenever I want to hightlight references to local variables so having it select every single occurence within other tokens would be distracting. The Ctrl+D rename tool should work within tokens though because it allows you some hacking that wouldn't be possible otherwise.

**Comment by aaronventure** [comment]
Fair point. But Sublime allows you to skip the last highlighted instance with CTRL+K, and go back with CTRL+U.

Would having matching token selection like I described at CTRL+SHIFT+D be too much of an ask?
