### ISSUE TITLE
[lol] Performing modulo on Message.getControllerValue() in onController() crashes HISE 

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#458]
1. Open HISE
2. Paste this into onController(): `Message.getControllerValue() % 0.1;`
3. Touch any controller

9e9641d80493a841b6750bea1c9f29f5cfc0da56

**Comment by christoph-hart** [comment]
Weird, doesn't happen here. What happens if you paste in `0 % 0.1;` into the onInit callback. Does it crash on compile? Does it crash if you put in `Message.getControllerValue() / 0`?

BTW, the modulo operator is only supposed to work with integer values (hence it gets truncated down to zero, you might want to use `Math.fmod()` instead.

**Comment by christoph-hart** [comment]
Checked on macOS this morning, but on Windows I can recreate it. Should be fixed now - it was in fact rounding down to zero but it didn't catch the divide by zero properly and Windows doesn't fuck around with divide by zero.

**Comment by aaronventure** [comment]
Now that you mention it, it's unrelated to this specific issue but I notice some warnings in VS2022 as I'm building HISE regarding divides by 0.

1>F:\HISE\HISE Source\JUCE\modules\juce_graphics\images\juce_Image.cpp(269): warning C4723: potential divide by 0
1>F:\HISE\HISE Source\JUCE\modules\juce_graphics\images\juce_Image.cpp(270): warning C4723: potential divide by 0

Don't know if that's got any impact whatsoever in practice.
