### ISSUE TITLE
[UX/ScriptNode] Collapsing a node or any of its parents hides connection info on parameters of non-collapsed nodes

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#539]
The cable graphic disappearing is debatable (there should still be a visual representation of the source or target... maybe a connection to the collapsed node when hovering the parameter?), but the icon underneath a connected parameter, as well as any connection info in the node properties (right click) disappears.

**Comment by christoph-hart** [comment]
Yup, I feel you here, that's super annoying. So I've made these changes:

![image](https://github.com/user-attachments/assets/2621089d-3372-40ac-983e-0af75905f9fd)

- if a source node is not visible, it will still show a white circle indicating that it's automated.
- if you hover over the knob, the tooltip will tell you the modulation source
- it will also show a red overlay over the source node. If the source node itself is not visible, it will search for the first parent that is visible so that you always see where it goes.
- if you double click on the slider it will not remove the connection, but unfold all nodes to show the actual source. This replaces the operation of deleting the modulation connection which is usually performed by the double click but I think it's OK as it resembles the double click to fold behaviour.

If the connection source is the parent macro parameter, it will just show the parameters.
