### ISSUE TITLE
ScriptWatchTable Breaks For Whatever Reason (.json included)

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#549]
So if I delete my editorData.json, the watchtable is functional again. If I put it back, it's broken.

Here's the JSON.

[editorData.json](https://github.com/user-attachments/files/15979400/editorData.json)

macOS 14.5.
2ec67045ee9d04fab2232faf5d29c6b8dfa558f4

**Comment by davidhealey** [comment]
Do a diff between the working one and the none-working one

**Comment by ustk** [comment]
So it appears `Folded` is `true` when the WatchTable don't show.
Set it manually to `1`-> the table disappears, back to `0`-> the table's back again

However the problem seems random. I tried to fold and quit, fold, unfold, quit, etc... 
I couldn't find a pattern to reproduce the issue.

So the question is, why the heck `Folded`sets to `1`?

<img width="377" alt="Screenshot 2024-07-08 at 17 45 23" src="https://github.com/christophhart/HISE/assets/50467457/40883bfe-2ad8-4ee9-94c2-c10797d6cd37">

**Comment by christoph-hart** [comment]
Good detective work, not sure how that folded flag could be set in a tab container, but I'm forcing it to be false on load, so it should never occur again.
