### ISSUE TITLE
add lv2 plugin suport

### ISSUE THREAD

**Issue by Reaper10** [christophhart/HISE#75]
add lv2 suport

http://lv2plug.in/
https://en.wikipedia.org/wiki/LV2

**Comment by christophhart** [comment]
Unfortunately, JUCE doesn't support this yet and writing a wrapper from scratch for this plugin format is way too complex.

**Comment by Reaper10** [comment]
https://forum.juce.com/t/juce-lv2-plugin-wrapper/14209/4

**Comment by unfa** [comment]
I'd also love LV2 export.
Also - it would open up the road to possibly export MOD Duo / MOD Duo X plug-ins!

**Comment by davidhealey** [comment]
I think this is beyond the scope of HISE. But if you want to try it there is a fork of JUCE with LV2 support - https://github.com/lv2-porting-project/JUCE

**Comment by unfa** [comment]
Thanks! I'm no developer, so I can't really make this work myself, but would the HISE devs be willing to accept a contributon if someone was to make LV2 export work?

**Comment by davidhealey** [comment]
As far as I know there isn't really anything that can be added to HISE to get it to export to LV2. The export functionality is provided by JUCE so LV2 export support would need to be added there. I'd like to see LV2 support as well so when I come to build my next project I'll have a play around with the info in the links I found before and see if I can get it to work.

**Comment by mxmilkiib** [comment]
Aside from https://github.com/lv2-porting-project/JUCE from @kottv, there is https://github.com/DISTRHO/JUCE by @falktx and now https://github.com/Chowdhury-DSP/DISTRHO-JUCE/commits/distrho-fork-lv2 from @jatinchowdhury18, all which can export to LV2, so could one of these be used by HISE, or is how HISE exports too different a form of "export"?

**Comment by frink** [comment]
This seems kind of in limbo. @christoph-hart said he didn't want to implement but didn't preclude the possibility of a community PR as @unfa mentioned. I don't have time or I'd take a scratch at this myself. @falkTX would be one person that can probably speak to this most directly on the difficulty of this because he's already done it two different ways from the looks of things...

I move that we reopen this issue because of the interest and the forward momentum in the projects @mxmilkiib and @davidhealey mentioned. However, until this becomes an easy thing in JUCE and acceptable or encouraged by ROLI (the new gatekeepers of this space) I don't know that it's worth spending much time just yet.

However, I'd add this to issues tag **help-wanted** if we had such a section.

**Comment by davidhealey** [comment]
> ROLI (the new gatekeepers of this space)

PACE now - https://www.synthtopia.com/content/2020/04/22/pace-acquires-juce-audio-development-platform-from-roli/

**Comment by falkTX** [comment]
I am all for having LV2 in juce, but they are not willing to share the work they already did it seems..
My idea would be to put any needed changes for backwards compatibility on top of what they already did, as otherwise 2 lv2 wrappers are being worked on at the same time which sounds extremely wasteful.

So I am on hold waiting to see if/when they will release their side of the lv2 wrapper (which according to a thread in KVR was pretty much already complete).
If there are no news in 2-3 months, I will revisit my JUCE fork and rework the lv2 wrapper to be more alike the other ones from the JUCE side.

**Comment by frink** [comment]
> I am all for having LV2 in juce, but they are not willing to share the work they already did it seems..

Ugh!

**Comment by Kirtai** [comment]
I believe JUCE now supports LV2

**Comment by davidhealey** [comment]
> I believe JUCE now supports LV2

JUCE 6?

**Comment by mxmilkiib** [comment]
Yup https://github.com/juce-framework/JUCE/issues/123

**Comment by falkTX** [comment]
that is JUCE7, not JUCE6. JUCE6 is not maintained anymore

**Comment by mxmilkiib** [comment]
Whoops. CMake was the big JUCE6 thing, not LV2.
